# rose-pine-dawn
[colors]
foreground = "#575279"
background = "#faf4ed"
cursor_bg = "#9893a5"
cursor_border = "#9893a5"
cursor_fg = "#575279"
selection_bg = "#dfdad9"
selection_fg = "#575279"

# ansi = {"black", "maroon", "green", "olive", "navy", "purple", "teal", "silver"},
# brights = {"grey", "red", "lime", "yellow", "blue", "fuchsia", "aqua", "white"},

ansi = ["#f2e9de", "#b4637a", "#286983", "#ea9d34", "#56949f", "#907aa9", "#d7827e", "#575279"]
brights = ["#6e6a86", "#b4637a", "#286983", "#ea9d34", "#56949f", "#907aa9", "#d7827e", "#575279"]
